name: 'CI Pipeline'
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  # Install Node.js and dependencies
  ci:
    strategy:
      matrix:
        NODE_VERSION:
          - '20'
          - '22'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci]'

      - uses: actions/checkout@v4

      - name: '🧩 Install Node (${{ matrix.NODE_VERSION }})'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.NODE_VERSION }}'

      - name: '📦 Install dependencies'
        run: yarn install --frozen-lockfile

      - name: '📕 Linting'
        run: yarn ci:lint

      # Start to run our inline jobs
      # Vitest
      - name: '🧪 Running tests'
        run: yarn ci:test